import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { Explorer } from "@/components/Explorer";
import { CoverageTable } from "@/components/CoverageTable";
import { loadResults, loadTopology, loadUnmapped, loadCalibration } from "@/lib/data";
import { pct } from "@/lib/scale";

function languageMeta() {
  // Mirrors harness/languages.py. Regenerated by scripts/build-languages.mjs.
  const path = join(process.cwd(), "public", "languages.json");
  if (!existsSync(path)) return { supported: {}, clips: {} };
  return JSON.parse(readFileSync(path, "utf8")) as {
    supported: Record<string, boolean>;
    clips: Record<string, number>;
  };
}

export default function Home() {
  const results = loadResults();
  const topology = loadTopology();
  const unmapped = loadUnmapped();
  const calibration = loadCalibration() as
    | { approach_1?: number; district_mean?: number; district_std?: number;
        inter_annotator_wer?: number; districts?: number; scored?: number }
    | null;
  const { supported, clips } = languageMeta();

  const unsupportedCount = Object.values(supported).filter((v) => !v).length;
  const totalLanguages = Object.keys(supported).length;

  return (
    <main className="mx-auto max-w-6xl px-6 py-16">
      <header className="mb-16 max-w-2xl">
        <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">kya bola?</h1>
        <p className="mt-4 text-lg text-[var(--muted)]">
          Every speech recognition vendor reports one accuracy number per language.
          Hindi in Delhi and Hindi in Araria are not the same problem, and a single
          number hides the difference. This measures it district by district.
        </p>
        {totalLanguages > 0 && (
          <p className="mt-4 text-lg text-[var(--muted)]">
            It also asks a question nobody has published an answer to. The corpus
            behind this contains{" "}
            <strong className="text-[var(--text)]">{totalLanguages} languages</strong>.
            Commercial speech APIs officially support{" "}
            <strong className="text-[var(--text)]">
              {totalLanguages - unsupportedCount}
            </strong>{" "}
            of them. Here is what happens to the other{" "}
            <strong className="text-[var(--text)]">{unsupportedCount}</strong>.
          </p>
        )}
      </header>

      <section className="mb-16">
        <h2 className="mb-1 text-2xl font-semibold">The map</h2>
        <p className="mb-6 text-[var(--muted)]">
          Error rate per district. Greener is better.
        </p>
        <Explorer topology={topology} runs={results.runs} unmapped={unmapped} />
      </section>

      {results.runs.length > 0 && (
        <section className="mb-16">
          <h2 className="mb-1 text-2xl font-semibold">The coverage gap</h2>
          <p className="mb-6 max-w-2xl text-[var(--muted)]">
            Languages an API does not claim to support are still sent to it, with
            language detection on. A refusal or an empty answer counts as a failed
            clip, because that is what a developer building for those speakers
            would experience.
          </p>
          <CoverageTable runs={results.runs} supported={supported} clipCounts={clips} />
        </section>
      )}

      {calibration && (
        <section className="mb-16 max-w-2xl">
          <h2 className="mb-1 text-2xl font-semibold">Is this trustworthy?</h2>
          <p className="mb-4 text-[var(--muted)]">
            Before measuring anything new, this harness reproduced a published
            result. The Vaani team benchmarked Sarvam Saaras v3 on their own Hindi
            evaluation set and reported a district mean word error rate of 18.3%
            with a standard deviation of 4.6. Running their clips through this
            pipeline gives:
          </p>
          <dl className="space-y-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] p-5">
            <div className="flex justify-between">
              <dt className="text-[var(--muted)]">district mean, ours</dt>
              <dd className="tabular font-medium">
                {pct(calibration.district_mean)}
                {calibration.district_std != null &&
                  ` +/- ${(calibration.district_std * 100).toFixed(1)}`}
              </dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-[var(--muted)]">district mean, published</dt>
              <dd className="tabular font-medium">18.3% +/- 4.6</dd>
            </div>
            <div className="flex justify-between border-t border-[var(--border)] pt-2">
              <dt className="text-[var(--muted)]">
                disagreement between two human transcribers
              </dt>
              <dd className="tabular font-medium">{pct(calibration.inter_annotator_wer)}</dd>
            </div>
          </dl>
          <p className="mt-4 text-sm text-[var(--muted)]">
            That last row is the floor. Two people transcribing the same audio
            disagree by that much, so no model can score below it and no gap
            narrower than it is a real difference between two systems.
          </p>
        </section>
      )}

      <footer className="border-t border-[var(--border)] pt-8 text-sm text-[var(--muted)]">
        <p>
          Built on{" "}
          <a
            className="underline decoration-[var(--border)] underline-offset-4 hover:text-[var(--text)]"
            href="https://huggingface.co/datasets/ARTPARK-IISc/Vaani"
          >
            Project Vaani
          </a>{" "}
          by ARTPARK and IISc, used under CC-BY-4.0. Method and caveats in the{" "}
          <a
            className="underline decoration-[var(--border)] underline-offset-4 hover:text-[var(--text)]"
            href="https://github.com/reetbatra/kya-bola"
          >
            repository
          </a>
          .
        </p>
        <p className="mt-2">
          Audio is spontaneous, image-prompted speech recorded in real conditions,
          not read speech in a studio. Error rates here are legitimately higher than
          the numbers vendors publish on clean benchmarks. That is the point.
        </p>
      </footer>
    </main>
  );
}
